// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table customers_schema_v1 (___id:string, ___source:string, ___type:string, ___time:datetime, ___subject:string, Customer_id:string, Name:string, Email:string, City:string, Created_at:string) 
.create-merge table Orders (order_id:string, customer_id:string, product:string, quantity:long, price:real, order_timestamp:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table ['transactions'] (transaction_id:string, order_id:string, payment_method:string, transaction_amount:real, transaction_status:string, transaction_timestamp:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
